format = """
$time
[▓](fg:#9257E6 bg:#9B89E0)\
[▓](fg:#9B89E0 bg:#BD92F8)\
[ 󱃮 ](fg:black bg:#BD92F8)\
[ ](fg:#BD92F8 bg:#7880CF)\
$directory\
[ ](fg:#7880CF bg:#FF78C5)\
[ ](fg:#FF78C5 bg:#ff4895)\
[ ](fg:#ff4895 bg:#FF7C6C)\
[ ](fg:#FF7C6C)\

"""

[directory]
format = "[ $path ](fg:black bg:#7880CF)"
truncation_length = 3
truncation_symbol = "…/"


[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](#a0a9cb)]($style)'
